---
name: 'Create Release'

on:
  workflow_dispatch:
  push:
    tags:
      - '*'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: write-all
jobs:
  create-release:
    name: 'Create Release'
    runs-on: 'ubuntu-latest'

    outputs:
      version: ${{ steps.read_version.outputs.version }}
      zip_name: ${{ steps.zip_project.outputs.zip_name }}

    steps:
      - name: ‚¨áÔ∏è Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ü§î Read version and project name from package.json
        id: read_version
        run: |

          VERSION=$(jq -r '.version' < package.json)
          PROJECT_NAME=$(jq -r '.name' < package.json)
          echo "Version is $VERSION"
          echo "Project name is $PROJECT_NAME"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "project_name=$PROJECT_NAME" >> $GITHUB_OUTPUT

      - name: ü§û Install dependencies
        run: |
          [ -f "package.json" ] && npm install || echo "No package.json file found"
          [ -f "composer.json" ] && composer install --no-dev || echo "No composer.json file found"

      - name: üìö Convert Readme.md to WordPress Readme
        uses: everpress-co/action-md2wp@main

      - name: üèóÔ∏è Build
        run: |
          npm run build --no-dev
          ls -al

      - name: üßπ Cleanup
        run: |
          echo "Cleanup"
          rm -f README.md

      - name: üóúÔ∏è Zip the contents of the dist directory with project name and version
        id: zip_project
        run: |
          ZIP_NAME="${{ steps.read_version.outputs.project_name }}.zip"
          npm run plugin-zip
          echo "zip_name=$ZIP_NAME" >> $GITHUB_OUTPUT
          ls -al

      - name: üì¶ Create Release
        if: ${{ !env.ACT }}
        uses: 'marvinpinto/action-automatic-releases@v1.2.1'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          prerelease: false
          files: |
            ${{ steps.read_version.outputs.project_name }}.zip

  deploy-to-wordpress:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Build # Remove or modify this step as needed
        run: |
          echo "HH"
          ls -al
          exit 1

      - name: WordPress Plugin Deploy
        if: ${{ !env.ACT }}
        uses: everpress-co/action-wordpress-plugin-deploy@main
        with:
          generate-zip: true
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
